def list_comprehension_exercise_1():
    ...
def list_comprehension_exercise_2():
    ...
def list_comprehension_exercise_3():
    ...
def list_comprehension_exercise_4():
    ...
def list_comprehension_exercise_5(sentence):
    ...
def list_comprehension_exercise_6(sentence):
    ...